version: '3.4'

services:
  mutagen:
    container_name: ${COMPOSE_PROJECT_NAME:-unnamed}_mutagen_${COMPOSE_PROJECT_PHP_VERSION:-7.2}_${COMPOSE_PROJECT_NODE_VERSION:-12.22.12}
    build:
      context: "${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/php-node-akeneo3"
      args:
        PHP_VERSION: ${COMPOSE_PROJECT_PHP_VERSION:-7.2}
        NODE_VERSION: ${COMPOSE_PROJECT_NODE_VERSION:-12.22.12}
        PHP_USER_NAME: ${COMPOSE_PROJECT_PHP_USER_NAME:-developer}
        PHP_USER_GROUP: ${COMPOSE_PROJECT_PHP_USER_GROUP:-developer}
        PHP_UID: ${COMPOSE_PROJECT_PHP_UID:-1000}
        PHP_GID: ${COMPOSE_PROJECT_PHP_GID:-1000}
    user: "${COMPOSE_PROJECT_USER_NAME:-developer}"
    volumes:
      - 'appcode:/var/www'
    command: "bash -c 'chmod 0777 /var/www; sleep infinity'"
    working_dir: '/var/www'
    networks:
      - 'appnet'
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  cli:
    depends_on:
      mutagen:
        condition: service_started

volumes:
  appcode:
    driver: local
    driver_opts: {}
