#!/bin/bash
set -e
#set -x
export COMPOSE_PROJECT_MODE=${COMPOSE_PROJECT_MODE-default}
export COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME-$(basename $(pwd))}

DOCKER_COMPOSE_BIN="${DOCKER_COMPOSE_BIN-$(which docker-compose)}";
if [[ -f "docker-compose.yml" ]]; then
  DOCKER_COMPOSE_BIN="${DOCKER_COMPOSE_BIN} -f docker-compose.yml"
fi

if [[ "$COMPOSE_PROJECT_MODE" == "mutagen" ]]; then
  if docker volume ls | grep "${COMPOSE_PROJECT_NAME}_appcode" > /dev/null; then
    if [[ $(docker volume inspect -f '{{ .Options.type }}' ${COMPOSE_PROJECT_NAME}_appcode) == "nfs" ]]; then
      docker volume rm ${COMPOSE_PROJECT_NAME}_appcode
    fi
  fi
  if [[ -f "docker-compose-mutagen.yml" ]]; then
      DOCKER_COMPOSE_BIN="${DOCKER_COMPOSE_BIN} -f docker-compose-mutagen.yml"
  fi

  DOCKER_CONTAINER_NAME_MUTAGEN=$(docker inspect -f '{{.Name}}' $(${DOCKER_COMPOSE_BIN} ps -q mutagen) | cut -c2-)
  if mutagen sync list | grep -i "Name: ${COMPOSE_PROJECT_NAME}-appcode"; then
    mutagen sync terminate ${COMPOSE_PROJECT_NAME}-appcode
  fi
  mutagen sync create --ignore-vcs --symlink-mode=ignore --name=${COMPOSE_PROJECT_NAME}-appcode $(pwd)/www docker://linuxbrew@${DOCKER_CONTAINER_NAME_MUTAGEN}/var/www
fi
