FROM docker.elastic.co/elasticsearch/elasticsearch:7.10.2
LABEL name="elasticsearch:7.10.2-magento2"
RUN bin/elasticsearch-plugin install analysis-icu
RUN bin/elasticsearch-plugin install analysis-phonetic
